In [1]:
import numpy


In [2]:
array1 = numpy.array([2,3,5,7,11,13,17,19,23,29,31])


In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(11,)

In [6]:
array2 = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [7]:
type(array2)

numpy.ndarray

In [8]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
array2.shape

(3, 4)

In [10]:
array2.size

12

In [11]:
array1.size

11

##  균일할 값으로 생성
### numpy 모듈의 full 메소드를 사용하면, 모든 값이 같은 numpy array를 생성할 수 있다.


In [12]:
array1 = numpy.full(6,7)
print(array1)

[7 7 7 7 7 7]


### 모든 값이 0인 numpy array 생성, 모든 값이 1인 numpy array 생성

In [16]:
array1 = numpy.full(6,0)
array2 = numpy.zeros(6,dtype=int)
print(array1)
print()
print(array2)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


In [17]:
array1 = numpy.full(6,1)
array2 = numpy.ones(6,dtype = int)
print(array1)
print()
print(array2)

[1 1 1 1 1 1]

[1 1 1 1 1 1]


## 랜덤한 값들로 생성
### numpy의 random 모듈의 random 함수를 사용하면 된다.

In [18]:
array1 = numpy.random.random(6)
array2 = numpy.random.random(6)
print(array1)
print()
print(array2)

[0.2921024  0.38846727 0.19128946 0.58584262 0.76066464 0.28975189]

[0.0713046  0.54253749 0.07533999 0.34585286 0.41272774 0.98429028]


## 연속된 값들이 담긴 numpy array 생성
### numpy 모듈의 arrange 함수를 사용하면 연속된 값들이 담겨 있는 numpy array를 생성할 수 있다.

In [19]:
array1 = numpy.arange(6)
print(array1)

[0 1 2 3 4 5]


In [20]:
array2 = numpy.arange(2,7)
print(array2)

[2 3 4 5 6]


In [21]:
array3 = numpy.arange(3,17,3)
print(array3)

[ 3  6  9 12 15]


## numpy 별명 만들기

In [22]:
import numpy as np


In [23]:
import matplotlib.pyplot as plt

In [24]:
arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [25]:
arr = np.arange(1,101,3)
arr

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [26]:
array1 = np.array([2,3,4,5,6,7,8,9,0])
array1[0]

2

In [28]:
array1[-1]

0

In [32]:
array1[[1,3,4]]

array([3, 5, 6])

In [33]:
array2 = np.array([2,1,3])

In [35]:
array1[array2]

array([4, 3, 5])

In [36]:
array1[0:7]

array([2, 3, 4, 5, 6, 7, 8])

In [37]:
array1[2:11:2]

array([4, 6, 8, 0])

In [38]:
array1

array([2, 3, 4, 5, 6, 7, 8, 9, 0])

In [39]:
array1*2

array([ 4,  6,  8, 10, 12, 14, 16, 18,  0])

In [41]:
array1 / 2

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 0. ])

In [42]:
array1

array([2, 3, 4, 5, 6, 7, 8, 9, 0])

In [46]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
array1 = np.arange(10)
array2 = np.arange(10,20)


In [44]:
array1+array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [45]:
array1*array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [48]:
revenue_in_yen = np.array([
    300000,3200000,320000,340000,
    440000,140000,180000,340000
])
month_revenue = 10.08 * revenue_in_yen
month_revenue

array([ 3024000., 32256000.,  3225600.,  3427200.,  4435200.,  1411200.,
        1814400.,  3427200.])

In [51]:
revenue_in_us = np.array([1600,1600,1920,603,
                         345,123,1325,1789])
month_revenue_us = 1130 * revenue_in_us
totals = month_revenue_us + month_revenue

In [52]:
totals

array([ 4832000., 34064000.,  5395200.,  4108590.,  4825050.,  1550190.,
        3311650.,  5448770.])

In [53]:
array1 > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [54]:
array1 % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [55]:
booleans = np.array([True,True,True,True,True,False,False,False,True])

In [57]:
np.where(booleans)

(array([0, 1, 2, 3, 4, 8], dtype=int64),)

In [58]:
np.where(array1>4)

(array([5, 6, 7, 8, 9], dtype=int64),)

In [5]:
import numpy as np
filter = np.where(array1>4)
array1[filter]

array([5, 6, 7, 8, 9])

In [60]:
revenue_in_yen = [300000,200000,500000,120000
    
]
array = np.array(revenue_in_yen)
filter = np.where(array <= 200000)
array[filter]


array([200000, 120000])

In [67]:
arrat = np.arange(10000000)  # 파이썬보다 빠르지만 값을 추가하고 제거하고 다양한 값을 가질때는 파이썬 밭 계산이 많고 복잡 행렬일때는 넘파이
arrat

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

##  넘파이 기본 통계 기능
### 최대값,최솟값 ,평균,**중앙값**,표준편차,분산

In [70]:
print(array1.max())
print(array1.min())
print(array1.mean())
print(np.median(array1))
print(array1.std())
print(array1.var())


9
0
4.5
4.5
2.8722813232690143
8.25
